// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef AwayWindow_h
#define AwayWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *awayMWin;
#include <FL/Fl_Input.H>
extern void fAwayMsg(Fl_Input*, void*);
extern Fl_Input *txtAwayMsg;
Fl_Double_Window* awayWindow();
#endif
