// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "AwayWindow.h"

Fl_Double_Window *awayMWin=(Fl_Double_Window *)0;

Fl_Input *txtAwayMsg=(Fl_Input *)0;

Fl_Double_Window* awayWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = awayMWin = new Fl_Double_Window(240, 40, "Away Message");
    w = o;
    { Fl_Input* o = txtAwayMsg = new Fl_Input(0, 15, 240, 25, "  Away Message:");
      o->callback((Fl_Callback*)fAwayMsg);
      o->align(FL_ALIGN_TOP_LEFT);
      o->when(FL_WHEN_ENTER_KEY);
    }
    o->end();
  }
  return w;
}
