// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef ui_fl_h
#define ui_fl_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *dnflWindow;
#include <FL/Fl_Menu_Button.H>
extern Fl_Menu_Button *currentBuddy;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *textOut;
#include <FL/Fl_Input.H>
extern Fl_Input *input;
#include <FL/Fl_Button.H>
extern Fl_Button *sendButton;
Fl_Double_Window* ui_fl();
#endif
