// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef AutoConnYNWindow_h
#define AutoConnYNWindow_h
#include <FL/Fl.H>
class AutoConnYNWindow;
#include <FL/Fl_Double_Window.H>
extern void flACYNClose(Fl_Double_Window*, AutoConnYNWindow *);
#include <FL/Fl_Button.H>
extern void flACYNYes(Fl_Button*, AutoConnYNWindow *);
extern void flACYNNo(Fl_Button*, AutoConnYNWindow *);
#include <FL/Fl_Output.H>

class AutoConnYNWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *autoConnYNWindow;
  Fl_Button *btnYes;
  Fl_Button *btnNo;
  char *hostname;
};
#endif
