// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "AutoConnYNWindow.h"
#include <string>

Fl_Double_Window* AutoConnYNWindow::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = autoConnYNWindow = new Fl_Double_Window(310, 80, "Autoconnection");
    w = o;
    o->color(FL_FOREGROUND_COLOR);
    o->callback((Fl_Callback*)flACYNClose, (void*)(this));
    { Fl_Button* o = btnYes = new Fl_Button(0, 55, 155, 25, "Yes");
      o->callback((Fl_Callback*)flACYNYes, (void*)(this));
    }
    { Fl_Button* o = btnNo = new Fl_Button(155, 55, 155, 25, "No");
      o->callback((Fl_Callback*)flACYNNo, (void*)(this));
    }
    { Fl_Output* o = new Fl_Output(0, 0, 310, 50);
      o->type(12);
      o->box(FL_NO_BOX);
      o->textcolor(7);
      o->wrap(1);
      std::string val = std::string("Would you like to automatically connect to ") + std::string(hostname) + std::string(" in the future?");
      o->value(val.c_str());
    }
    o->end();
  }
  return w;
}
