// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef AutoConnWindow_h
#define AutoConnWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern void flAddAC(Fl_Input*, void*);

class AutoConnWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *autoConnWindow;
  Fl_Input *hostname;
};
#endif
