// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "AutoConnWindow.h"

Fl_Double_Window* AutoConnWindow::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = autoConnWindow = new Fl_Double_Window(310, 40, "New Autoconnection");
    w = o;
    o->color(FL_FOREGROUND_COLOR);
    o->user_data((void*)(this));
    { Fl_Input* o = hostname = new Fl_Input(0, 15, 310, 25, "  Hostname:");
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->callback((Fl_Callback*)flAddAC);
      o->align(FL_ALIGN_TOP_LEFT);
      o->when(FL_WHEN_ENTER_KEY);
    }
    o->end();
  }
  return w;
}
