// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef BuddyWindow_h
#define BuddyWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
extern void estConn(Fl_Input*, void*);

class BuddyWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *buddyWindow;
  Fl_Choice *onlineList;
  Fl_Input *connectInput;
};
#endif
