// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "ChannelWindow.h"

Fl_Double_Window* ChannelWindow::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = channelWindow = new Fl_Double_Window(420, 315, "User");
    w = o;
    o->callback((Fl_Callback*)closeChat, (void*)(this));
    { Fl_Input* o = textIn = new Fl_Input(0, 290, 420, 25);
      o->callback((Fl_Callback*)sendInput);
      o->when(FL_WHEN_ENTER_KEY);
    }
    { Fl_Tile* o = new Fl_Tile(0, 0, 420, 290);
      userList = new Fl_Browser(0, 0, 100, 290);
      textOut = new Fl_Help_View(100, 0, 320, 290);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  return w;
}
