// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "DHTWindow.h"

Fl_Double_Window* DHTWindow::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = tWin = new Fl_Double_Window(400, 50, "DHT Action");
    w = o;
    o->user_data((void*)(this));
    { Fl_Progress* o = tBar = new Fl_Progress(0, 0, 400, 50, "DHT Action");
      o->selection_color((Fl_Color)4);
      o->minimum(0.0); o->maximum(100.0); o->value(0.0);
    }
    o->set_modal();
    o->end();
  }
  return w;
}
