// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef DHTWindow_h
#define DHTWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Progress.H>

class DHTWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *tWin;
  Fl_Progress *tBar;
};
#endif
