// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef NameWindow_h
#define NameWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern void mainWinClosed(Fl_Double_Window*, void*);
#include <FL/Fl_Input.H>
extern void setName(Fl_Input*, void*);

class NameWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *nameWindow;
  Fl_Input *nameIn;
};
#endif
