// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef QWindow_h
#define QWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>

class QWindow {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *qWin;
  Fl_Input *qInp;
  Fl_Button *okButton;
  Fl_Button *cancelButton;
};
void destroyQWin(Fl_Widget *o, void *qw);
#endif
