// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "QWindow.h"

Fl_Double_Window* QWindow::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = qWin = new Fl_Double_Window(400, 70, "Q");
    w = o;
    o->user_data((void*)(this));
    { Fl_Input* o = qInp = new Fl_Input(0, 20, 400, 25, "Q?");
      o->align(FL_ALIGN_TOP_LEFT);
      o->when(FL_WHEN_ENTER_KEY);
    }
    okButton = new Fl_Button(0, 45, 200, 25, "OK");
    cancelButton = new Fl_Button(200, 45, 200, 25, "Cancel");
    o->set_modal();
    o->end();
  }
  return w;
}

void destroyQWin(Fl_Widget *o, void *qw) {
  if (qw) {
    QWindow *qwin = (QWindow *) qw;
    if (qwin->qWin) {
        qwin->qWin->hide();
        delete qwin->qWin;
    }
    delete qwin;
}
}
