// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "ui_fl.h"

Fl_Double_Window *dnflWindow=(Fl_Double_Window *)0;

Fl_Menu_Button *currentBuddy=(Fl_Menu_Button *)0;

Fl_Text_Display *textOut=(Fl_Text_Display *)0;

Fl_Input *input=(Fl_Input *)0;

Fl_Button *sendButton=(Fl_Button *)0;

Fl_Double_Window* ui_fl() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = dnflWindow = new Fl_Double_Window(440, 340);
    w = o;
    { Fl_Menu_Button* o = currentBuddy = new Fl_Menu_Button(0, 0, 440, 25);
    }
    textOut = new Fl_Text_Display(0, 25, 440, 290);
    input = new Fl_Input(0, 315, 380, 25);
    sendButton = new Fl_Button(380, 315, 60, 25, "Send");
    o->end();
  }
  return w;
}
